# -*- encoding: utf-8 -*-

=begin
#Catalog Inventory

#Catalog Inventory

The version of the OpenAPI document: 3.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

$:.push File.expand_path("../lib", __FILE__)
require "catalog_inventory-api-client-ruby/version"

Gem::Specification.new do |s|
  s.name        = "catalog_inventory-api-client-ruby"
  s.version     = CatalogInventoryApiClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["RedHatInsights Authors"]
  s.email       = ["support@redhat.com"]
  s.homepage    = "https://github.com/RedHatInsights/catalog_inventory-api-client-ruby"
  s.summary     = "Catalog Inventory Ruby Gem"
  s.description = "Ruby client gem to connect to RedHatInsights Catalog Inventory Service"
  s.license     = 'Apache-2.0'
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
