=begin
#Catalog Inventory

#Catalog Inventory

The version of the OpenAPI document: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CatalogInventoryApiClient::ServiceOfferingIconApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServiceOfferingIconApi' do
  before do
    # run before each test
    @api_instance = CatalogInventoryApiClient::ServiceOfferingIconApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServiceOfferingIconApi' do
    it 'should create an instance of ServiceOfferingIconApi' do
      expect(@api_instance).to be_instance_of(CatalogInventoryApiClient::ServiceOfferingIconApi)
    end
  end

  # unit tests for list_service_offering_icons
  # List ServiceOfferingIcons
  # Returns an array of ServiceOfferingIcon objects
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [ServiceOfferingIconsCollection]
  describe 'list_service_offering_icons test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_service_offering_icon
  # Show an existing ServiceOfferingIcon
  # Returns a ServiceOfferingIcon object
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @return [ServiceOfferingIcon]
  describe 'show_service_offering_icon test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_service_offering_icon_icon_data
  # Show an existing ServiceOfferingIcon IconData
  # Returns a ServiceOfferingIcon IconData
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'show_service_offering_icon_icon_data test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
