=begin
#Catalog Inventory

#Catalog Inventory

The version of the OpenAPI document: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CatalogInventoryApiClient::ServiceInventoryApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServiceInventoryApi' do
  before do
    # run before each test
    @api_instance = CatalogInventoryApiClient::ServiceInventoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServiceInventoryApi' do
    it 'should create an instance of ServiceInventoryApi' do
      expect(@api_instance).to be_instance_of(CatalogInventoryApiClient::ServiceInventoryApi)
    end
  end

  # unit tests for list_service_inventories
  # List ServiceInventories
  # Returns an array of ServiceInventory objects
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [ServiceInventoriesCollection]
  describe 'list_service_inventories test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_service_inventory_tags
  # List Tags for ServiceInventory
  # Returns an array of Tag objects
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [TagsCollection]
  describe 'list_service_inventory_tags test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_service_inventory
  # Show an existing ServiceInventory
  # Returns a ServiceInventory object
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @return [ServiceInventory]
  describe 'show_service_inventory test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for tag_service_inventory
  # Tag a ServiceInventory
  # Tags a ServiceInventory object
  # @param id ID of the resource
  # @param tag Tag attributes to add
  # @param [Hash] opts the optional parameters
  # @return [Array<Tag>]
  describe 'tag_service_inventory test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for untag_service_inventory
  # Untag a ServiceInventory
  # Untags a ServiceInventory object
  # @param id ID of the resource
  # @param tag Tag attributes to removed
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'untag_service_inventory test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
