=begin
#Catalog Inventory

#Catalog Inventory

The version of the OpenAPI document: 3.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CatalogInventoryApiClient::ServiceInstanceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServiceInstanceApi' do
  before do
    # run before each test
    @api_instance = CatalogInventoryApiClient::ServiceInstanceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServiceInstanceApi' do
    it 'should create an instance of ServiceInstanceApi' do
      expect(@api_instance).to be_instance_of(CatalogInventoryApiClient::ServiceInstanceApi)
    end
  end

  # unit tests for list_service_instance_service_credentials
  # List ServiceCredentials for ServiceInstance
  # Returns an array of ServiceCredential objects
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [ServiceCredentialsCollection]
  describe 'list_service_instance_service_credentials test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_service_instance_service_instance_nodes
  # List ServiceInstanceNodes for ServiceInstance
  # Returns an array of ServiceInstanceNode objects
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [ServiceInstanceNodesCollection]
  describe 'list_service_instance_service_instance_nodes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_service_instances
  # List ServiceInstances
  # Returns an array of ServiceInstance objects
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [ServiceInstancesCollection]
  describe 'list_service_instances test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_service_instance
  # Show an existing ServiceInstance
  # Returns a ServiceInstance object
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @return [ServiceInstance]
  describe 'show_service_instance test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
