=begin
#Catalog Inventory

#Catalog Inventory

The version of the OpenAPI document: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CatalogInventoryApiClient::ServiceOfferingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServiceOfferingApi' do
  before do
    # run before each test
    @api_instance = CatalogInventoryApiClient::ServiceOfferingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServiceOfferingApi' do
    it 'should create an instance of ServiceOfferingApi' do
      expect(@api_instance).to be_instance_of(CatalogInventoryApiClient::ServiceOfferingApi)
    end
  end

  # unit tests for applied_inventories_tags_for_service_offering
  # Invokes computing of ServiceInventories tags for given ServiceOffering
  # Returns an array of inventories tags
  # @param id ID of the resource
  # @param applied_inventories_parameters_service_plan Parameters defining input data for computing inventories
  # @param [Hash] opts the optional parameters
  # @return [Array<Tag>]
  describe 'applied_inventories_tags_for_service_offering test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_service_offering_service_credentials
  # List ServiceCredentials for ServiceOffering
  # Returns an array of ServiceCredential objects
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [ServiceCredentialsCollection]
  describe 'list_service_offering_service_credentials test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_service_offering_service_instances
  # List ServiceInstances for ServiceOffering
  # Returns an array of ServiceInstance objects
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [ServiceInstancesCollection]
  describe 'list_service_offering_service_instances test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_service_offering_service_offering_nodes
  # List ServiceOfferingNodes for ServiceOffering
  # Returns an array of ServiceOfferingNode objects
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [ServiceOfferingNodesCollection]
  describe 'list_service_offering_service_offering_nodes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_service_offering_service_plans
  # List ServicePlans for ServiceOffering
  # Returns an array of ServicePlan objects
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [ServicePlansCollection]
  describe 'list_service_offering_service_plans test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_service_offering_tags
  # List Tags for ServiceOffering
  # Returns an array of Tag objects
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [TagsCollection]
  describe 'list_service_offering_tags test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_service_offerings
  # List ServiceOfferings
  # Returns an array of ServiceOffering objects
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [ServiceOfferingsCollection]
  describe 'list_service_offerings test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for order_service_offering
  # Order an existing ServiceOffering
  # Returns a Task id
  # @param id ID of the resource
  # @param order_parameters_service_offering Order parameters defining the service and provider control
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'order_service_offering test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_service_offering
  # Show an existing ServiceOffering
  # Returns a ServiceOffering object
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @return [ServiceOffering]
  describe 'show_service_offering test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for tag_service_offering
  # Tag a ServiceOffering
  # Tags a ServiceOffering object
  # @param id ID of the resource
  # @param tag Tag attributes to add
  # @param [Hash] opts the optional parameters
  # @return [Array<Tag>]
  describe 'tag_service_offering test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for untag_service_offering
  # Untag a ServiceOffering
  # Untags a ServiceOffering object
  # @param id ID of the resource
  # @param tag Tag attributes to removed
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'untag_service_offering test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
