=begin
#Catalog Inventory

#Catalog Inventory

The version of the OpenAPI document: 3.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CatalogInventoryApiClient::ServiceOfferingNodeApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServiceOfferingNodeApi' do
  before do
    # run before each test
    @api_instance = CatalogInventoryApiClient::ServiceOfferingNodeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServiceOfferingNodeApi' do
    it 'should create an instance of ServiceOfferingNodeApi' do
      expect(@api_instance).to be_instance_of(CatalogInventoryApiClient::ServiceOfferingNodeApi)
    end
  end

  # unit tests for list_service_offering_node_service_credentials
  # List ServiceCredentials for ServiceOfferingNode
  # Returns an array of ServiceCredential objects
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [ServiceCredentialsCollection]
  describe 'list_service_offering_node_service_credentials test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_service_offering_nodes
  # List ServiceOfferingNodes
  # Returns an array of ServiceOfferingNode objects
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [ServiceOfferingNodesCollection]
  describe 'list_service_offering_nodes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_service_offering_node
  # Show an existing ServiceOfferingNode
  # Returns a ServiceOfferingNode object
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @return [ServiceOfferingNode]
  describe 'show_service_offering_node test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
