=begin
#Catalog Inventory

#Catalog Inventory

The version of the OpenAPI document: 3.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CatalogInventoryApiClient::TaskApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TaskApi' do
  before do
    # run before each test
    @api_instance = CatalogInventoryApiClient::TaskApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TaskApi' do
    it 'should create an instance of TaskApi' do
      expect(@api_instance).to be_instance_of(CatalogInventoryApiClient::TaskApi)
    end
  end

  # unit tests for list_tasks
  # List Tasks
  # Returns an array of Task objects
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The numbers of items to return per page.
  # @option opts [Integer] :offset The number of items to skip before starting to collect the result set.
  # @option opts [Object] :filter Filter for querying collections.
  # @option opts [Object] :sort_by The list of attribute and order to sort the result set by.
  # @return [TasksCollection]
  describe 'list_tasks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_task
  # Show an existing Task
  # Returns a Task object
  # @param id UUID of task
  # @param [Hash] opts the optional parameters
  # @return [Task]
  describe 'show_task test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_task
  # Update an existing Task
  # Updates a Task object
  # @param id UUID of task
  # @param task Task attributes to update
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_task test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
