=begin
#Catalog Inventory

#Catalog Inventory

The version of the OpenAPI document: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CatalogInventoryApiClient::IncrementalRefreshUploadTask
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IncrementalRefreshUploadTask' do
  before do
    # run before each test
    @instance = CatalogInventoryApiClient::IncrementalRefreshUploadTask.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IncrementalRefreshUploadTask' do
    it 'should create an instance of IncrementalRefreshUploadTask' do
      expect(@instance).to be_instance_of(CatalogInventoryApiClient::IncrementalRefreshUploadTask)
    end
  end
end
